configure: add -(no-)uchardet & -(no-)icu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,32 +1,141 @@
 #!/bin/sh
 
+BUILD_TREE=`/bin/pwd`
+SOURCE_TREE=`dirname $0`
+SOURCE_TREE=`cd "$SOURCE_TREE"; /bin/pwd`
 
+BUILD_PLUGINS=yes
+BUILD_EXAMPLES=yes
+BUILD_TESTS=yes
 
-#
-# Defaults
-#
+BUILD_UCHARDET=yes
+BUILD_ICU=auto
 
-OPTION_STATIC=no
-OPTION_QMAKE=`which qmake || which qmake-qt4` 2>/dev/null
+QMAKE_CONFIG=
+QMAKE_PARAMS=
+QMAKE_DEBUG=
+OPT_HELP=no
 
-OPTION_MAKE_PLUGINS=yes
-OPTION_MAKE_EXAMPLES=yes
-OPTION_MAKE_TESTS=yes
+QMAKE=`which qmake || which qmake-qt4` 2>/dev/null
 
-QMAKE_ARGS=
-QMAKE_CONF=
-PRO_FILE=`dirname $0`/communi.pro
+#-------------------------------------------------------------------------------
+# parse command line arguments
+#-------------------------------------------------------------------------------
 
+# parse the arguments, setting things to "yes" or "no"
+while [ "$#" -gt 0 ]; do
+    CURRENT_OPT="$1"
+    UNKNOWN_ARG=no
+    case "$1" in
+    #Qt style no options
+    -no-*)
+        VAR=`echo $1 | sed 's,^-no-\(.*\),\1,'`
+        VAL=no
+        ;;
+    #Qt style yes options
+    -uchardet|-icu|-static)
+        VAR=`echo $1 | sed 's,^-\(.*\),\1,'`
+        VAL=yes
+        ;;
+    -*)
+        VAR=`echo $1 | sed 's,^-\(.*\),\1,'`
+        VAL=unknown
+        ;;
+    *)
+        UNKNOWN_ARG=yes
+        ;;
+    esac
+    if [ "$UNKNOWN_ARG" = "yes" ]; then
+        echo "$1: unknown argument"
+        OPT_HELP=yes
+        ERROR=yes
+        shift
+        continue
+    fi
+    shift
 
+    UNKNOWN_OPT=no
+    case "$VAR" in
+    nomake)
+        case "$1" in
+        plugins)
+            BUILD_PLUGINS=no
+            shift
+            ;;
+        examples)
+            BUILD_EXAMPLES=no
+            shift
+            ;;
+        tests)
+            BUILD_TESTS=no
+            shift
+            ;;
+        *)
+            CURRENT_OPT="$1"
+            UNKNOWN_OPT=yes
+            ;;
+        esac
+        ;;
+    make)
+        case "$1" in
+        plugins)
+            BUILD_PLUGINS=yes
+            ;;
+        examples)
+            BUILD_EXAMPLES=yes
+            ;;
+        tests)
+            BUILD_TESTS=yes
+            ;;
+        *)
+            CURRENT_OPT="$1"
+            UNKNOWN_OPT=yes
+            ;;
+        esac
+        shift
+        ;;
+    static)
+        QMAKE_CONFIG="$QMAKE_CONFIG static"
+        ;;
+    qmake)
+        QMAKE_="$1"
+        shift
+        ;;
+    config)
+        QMAKE_CONFIG="$QMAKE_CONFIG $1"
+        shift
+        ;;
+    d)
+        QMAKE_DEBUG="$QMAKE_DEBUG -d"
+        ;;
+    uchardet)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            BUILD_UCHARDET=$VAL
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    icu)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            BUILD_ICU=$VAL
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    *)
+        UNKNOWN_OPT=yes
+        ;;
+    esac
+    if [ "$UNKNOWN_OPT" = "yes" ]; then
+        echo "${CURRENT_OPT}: unknown option"
+        OPT_HELP=yes
+        ERROR=yes
+    fi
+done
 
-#
-# Functions
-#
-
-help()
-{
-cat << END
-Usage: $0 [OPTION]...
+if [ "$OPT_HELP" = "yes" ]; then
+    cat << EOF
+Usage:  configure [options]
 
 Configure options:
 
@@ -37,103 +146,52 @@ Configure options:
                                make time (available parts: plugins examples tests)
     -nomake (part) ........... Exclude part from the list of parts to be built
 
-END
-}
+Additional options:
 
-error()
-{
-    echo "Error: $@"
-    exit 1
-}
+    -no-uchardet ............. Do not build uchardet support
+    -uchardet ................ Build uchardet support
 
-parse_make_part()
-{
-    case "$1" in
-        plugins)    OPTION_MAKE_PLUGINS="$2";;
-        examples)   OPTION_MAKE_EXAMPLES="$2";;
-        tests)      OPTION_MAKE_TESTS="$2";;
-        *)          error "Unknown make part: $1";;
-    esac
-}
+    -no-icu .................. Do not build ICU support
+    -icu ..................... Build ICU support
 
-add_qmake_config_arg()
-{
-    case "$1" in
-        yes)    QMAKE_CONF="$QMAKE_CONF $2"
-                QMAKE_ARGS="$QMAKE_ARGS -config $2";;
-        no)     QMAKE_CONF="$QMAKE_CONF $3"
-                QMAKE_ARGS="$QMAKE_ARGS -config $3";;
-        auto)   ;; # Do nothing
-        *)      error "Invalid value";;
-    esac
-}
-
-
-
-#
-# Parse arguments
-#
-
-while [ $# -gt 0 ] ; do
-    case "$1" in
-        -static)        OPTION_STATIC="yes";;
-        -qmake)         OPTION_QMAKE="$2"; shift;;
-        -config)        QMAKE_CONF="$QMAKE_CONF $2"
-                        QMAKE_ARGS="$QMAKE_ARGS -config $2";
-                        shift;;
-
-        -make)          parse_make_part "$2" "yes"; shift;;
-        -nomake)        parse_make_part "$2" "no"; shift;;
-
-        -help|-h)       help; exit;;
-        *)              error "Unknown option: $1. Please see $0 -help.";;
-    esac
-    shift
-done
-
-
-
-#
-# Static option
-#
-if [ "$OPTION_STATIC" = "yes" ]; then
-    QMAKE_CONF="$QMAKE_CONF static"
-    QMAKE_ARGS="$QMAKE_ARGS -config static"
+EOF
+    [ "x$ERROR" = "xyes" ] && exit 1
+    exit 0
 fi
 
+[ "$BUILD_PLUGINS" = "no" ] && QMAKE_PARAMS="$QMAKE_PARAMS -config no_plugins"
+[ "$BUILD_EXAMPLES" = "no" ] && QMAKE_PARAMS="$QMAKE_PARAMS -config no_examples"
+[ "$BUILD_TESTS" = "no" ] && QMAKE_PARAMS="$QMAKE_PARAMS -config no_tests"
 
+[ "$BUILD_UCHARDET" = "no" ] && QMAKE_PARAMS="$QMAKE_PARAMS -config no_uchardet"
+[ "$BUILD_ICU" = "no" ] && QMAKE_PARAMS="$QMAKE_PARAMS -config no_icu"
 
-#
-# Add qmake options
-#
-add_qmake_config_arg "$OPTION_MAKE_PLUGINS"  "plugins"  "no_plugins"
-add_qmake_config_arg "$OPTION_MAKE_EXAMPLES" "examples" "no_examples"
-add_qmake_config_arg "$OPTION_MAKE_TESTS"    "tests"    "no_tests"
-
-
-
-#
-# Run qmake
-#
-if [ ! -f "$OPTION_QMAKE" ]; then
+if [ ! -f "$QMAKE" ]; then
     echo "ERROR: Unable to find qmake. Try $0 -qmake /path/to/qmake."
     exit 1
 fi
 
-echo "Running $OPTION_QMAKE"
-$OPTION_QMAKE -r $QMAKE_ARGS $PRO_FILE
+echo
+echo "Running $QMAKE..."
 
+$QMAKE $QMAKE_DEBUG -r $QMAKE_PARAMS "CONFIG+=$QMAKE_CONFIG" $SOURCE_TREE/communi.pro
+if [ $? != 0 ]; then
+    echo "ERROR: qmake run failed."
+    exit 1
+fi
 
-
-#
-# Output summary
-#
 echo
 echo "Communi build configuration:"
-echo "Configuration ...................$QMAKE_CONF"
-echo "Plugins ......................... $OPTION_MAKE_PLUGINS"
-echo "Examples ........................ $OPTION_MAKE_EXAMPLES"
-echo "Tests ........................... $OPTION_MAKE_TESTS"
+if [ "$QMAKE_CONFIG" != "" ]; then
+    echo "Configuration ...................$QMAKE_CONFIG"
+fi
+echo "Plugins ......................... $BUILD_PLUGINS"
+if [ "$BUILD_PLUGINS" = "yes" ]; then
+    echo "  uchardet support .............. $BUILD_UCHARDET"
+    echo "  ICU support ................... $BUILD_ICU"
+fi
+echo "Examples ........................ $BUILD_EXAMPLES"
+echo "Tests ........................... $BUILD_TESTS"
 echo
 echo Communi is now configured for building. Just run \'make\'.
 echo
